export const paises = [
  'Afeganistão: Afegão',
  'Albânia: Albanês',
  'Alemanha: Alemão',
  'Andorra: Andorrano',
  'Angola: Angolano',
  'Antígua e Barbuda: Antiguano',
  'Arábia Saudita: Saudita',
  'Argélia: Argelino',
  'Argentina: Argentino',
  'Armênia: Armênio',
  'Austrália: Australiano',
  'Áustria: Austríaco',
  'Azerbaijão: Azerbaijano',
  'Bahamas: Bahamense',
  'Barém: Bareminho',
  'Bangladesh: Bangladesí',
  'Barbados: Barbadosense',
  'Bélgica: Belga',
  'Belize: Belizenho',
  'Benim: Beninês',
  'Bielorrússia: Bielorrusso',
  'Mianmar: Birmanês',
  'Bolívia: Boliviano',
  'Bósnia e Herzegovina: Bósnio',
  'Botsuana: Botsuanês',
  'Brasil: Brasileiro',
  'Brunei: Bruneano',
  'Bulgária: Búlgaro',
  'Burkina Faso: Burquinês',
  'Burundi: Burundiano',
  'Cabo Verde: Cabo-verdiano',
  'Camboja: Cambojano',
  'Camarões: Camaronês',
  'Canadá: Canadense',
  'Chade: Chadiano',
  'Chile: Chileno',
  'China: Chinês',
  'Chipre: Cipriota',
  'Cidade do Vaticano: Vaticano',
  'Colômbia: Colombiano',
  'Comores: Comorense',
  'Coreia do Norte: Norte-coreano',
  'Coreia do Sul: Sul-coreano',
  'Costa do Marfim: Marfinense',
  'Costa Rica: Costarriquenho',
  'Croácia: Croata',
  'Cuba: Cubano',
  'Dinamarca: Dinamarquês',
  'Dominica: Dominicano',
  'Equador: Equatoriano',
  'Egito: Egípcio',
  'El Salvador: Salvadorenho',
  'Emirados Árabes Unidos: Emiradense',
  'Eritreia: Eritreu',
  'Eslováquia: Eslovaco',
  'Eslovênia: Esloveno',
  'Espanha: Espanhol',
  'Estados Unidos: Estadunidense',
  'Estônia: Estoniano',
  'Etiópia: Etíope',
  'Filipinas: Filipino',
  'Finlândia: Finlandês',
  'Fiji: Fijiiano',
  'França: Francês',
  'Gabão: Gabonês',
  'Gâmbia: Gambiano',
  'Geórgia: Georgiano',
  'Gana: Ganês',
  'Granada: Granadino',
  'Grécia: Grego',
  'Guatemala: Guatemalteco',
  'Guiné: Guineano',
  'Guiné-Bissau: Guineense',
  'Guiné Equatorial: Equatoguineano',
  'Guiana: Guianense',
  'Haiti: Haitiano',
  'Honduras: Hondurenho',
  'Hungria: Húngaro',
  'Índia: Indiano',
  'Indonésia: Indonésio',
  'Irã: Iraniano',
  'Iraque: Iraquiano',
  'Irlanda: Irlandês',
  'Islândia: Islandês',
  'Ilhas Marshall: Marshallês',
  'Ilhas Salomão: Salomônico',
  'Israel: Israelita',
  'Itália: Italiano',
  'Jamaica: Jamaicano',
  'Japão: Japonês',
  'Jordânia: Jordaniano',
  'Cazaquistão: Cazaque',
  'Quênia: Queniano',
  'Quirguistão: Quirguiz',
  'Quiribati: Quiribatinês',
  'Kuwait: Kuwaitiano',
  'Laos: Laociano',
  'Lesoto: Lesotense',
  'Letônia: Letão',
  'Líbano: Libanês',
  'Libéria: Liberiano',
  'Líbia: Líbio',
  'Liechtenstein: Liechtensteiniano',
  'Lituânia: Lituano',
  'Luxemburgo: Luxemburguês',
  'Madagáscar: Malgaxe',
  'Malásia: Malaio',
  'Malaui: Malauí',
  'Maldivas: Maldivo',
  'Mali: Malinês',
  'Malta: Maltês',
  'Marrocos: Marroquino',
  'Maurício: Mauriciano',
  'Mauritânia: Mauritano',
  'México: Mexicano',
  'Micronésia: Micronésio',
  'Moldávia: Moldavo',
  'Mônaco: Monegasco',
  'Mongólia: Mongol',
  'Montenegro: Montenegrino',
  'Moçambique: Moçambicano',
  'Namíbia: Namibiano',
  'Nauru: Nauruanês',
  'Nepal: Nepalês',
  'Nicarágua: Nicarenho',
  'Níger: Nigeriano',
  'Nigéria: Nigeriano',
  'Noruega: Norueguês',
  'Nova Zelândia: Neozelandês',
  'Omã: Omanense',
  'Países Baixos: Holandês',
  'Paquistão: Paquistanês',
  'Palau: Palauano',
  'Palestina: Palestino',
  'Panamá: Panamenho',
  'Papua-Nova Guiné: Papua-novoguineano',
  'Paraguai: Paraguaiano',
  'Peru: Peruano',
  'Polônia: Polonês',
  'Portugal: Português',
  'Reino Unido: Britânico',
  'República Centro-Africana: Centro-africano',
  'República Tcheca: Tcheco',
  'República Democrática do Congo: Congolês',
  'República Dominicana: Dominicana',
  'Romênia: Romeno',
  'Rússia: Russo',
  'Ruanda: Ruandês',
  'Samoa: Samoano',
  'São Cristóvão e Nevis: São-cristovense',
  'São Marino: Sanmarinense',
  'São Vicente e Granadinas: São-vicentino',
  'Santa Lúcia: Santalucense',
  'São Tomé e Príncipe: São-tomense',
  'Senegal: Senegalês',
  'Sérvia: Sérvio',
  'Seicheles: Seichelense',
  'Serra Leoa: Serleonês',
  'Singapura: Singapurense',
  'Síria: Sírio',
  'Somália: Somali',
  'Sri Lanka: Sri-lankês',
  'Suécia: Sueco',
  'Suíça: Suíço',
  'Suriname: Surinamês',
  'Tailândia: Tailandês',
  'Tanzânia: Tanzaniano',
  'Tajiquistão: Tajique',
  'Timor-Leste: Timorense',
  'Togo: Togolês',
  'Tonga: Tonganês',
  'Trindade e Tobago: Trinitense',
  'Tunísia: Tunisiano',
  'Turcomenistão: Turcomeno',
  'Turquia: Turco',
  'Tuvalu: Tuvaluanês',
  'Ucrânia: Ucraniano',
  'Uganda: Ugandense',
  'Uruguai: Uruguaio',
  'Uzbequistão: Uzbeque',
  'Vanuatu: Vanuatuense',
  'Vaticano: Vaticano',
  'Venezuela: Venezuelano',
  'Vietnã: Vietnamita',
  'Iêmen: Iemenita',
  'Jibuti: Djibutiano',
  'Zâmbia: Zambiano',
  'Zimbábue: Zimbabuense',
];